spring:
  datasource:
    url: jdbc:postgresql://192.168.63.130:5432/stock_data?currentSchema=stock
    username: postgres
    password: guilin@2022
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      connection-timeout: 30000

  jackson:
    deserialization:
      use-big-decimal-for-floats: true
    serialization:
      write-bigdecimal-as-plain: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 30


stock:
  path: "http://192.168.145.77:9000/api/public/"


task:
  enable: true
  us-enable: true